### ISSUE TITLE
Feature: syntax highlighting für JSON Ausgabe

### ISSUE THREAD

**Issue by mstein77** [tyrolite-studios/apixt#1]
Um die Lesbarkeit von JSON-Ausgaben zu erhöhen, soll das Ergebnis von `JSON.stringify(myJson, null, indentation) ` um span-Elemente ergänzt werden, welche null, booleans, strings, arrays, objekte ähnlich wie in einer IDE einfärben.

Es soll dafür eine Function `getStringifiedJSON(myJson, identation)` im util-Modul angelegt werden und entsprechend muit Jest-Tests abgedeckt werden. Die Klassennamen für die Einfärbung sollen Konstanten (z.B. COLOR_CLS_BOOL) sein, die auch für die Tests exportiert werden können und später durch tailwind-Namen ersetzt werden können.

Es kann davon ausgegangen werden, dass immer eine indentation >= 1 vorliegt.

**Comment by fatih-g** [comment]
Sooo, ich hätte dann schonmal einen Stand. 
Eigentlich sollte mein bisheriges Skript bereits die Klassen so vergeben, wie gewünscht. Ich habe mich orientiert an dem Highlighting vom Bild, was ich anhänge. Eine Frage die ich hätte wäre mit den Branches etc, benutzt du git flow ?

Was mir jetzt dann noch fehlt ist das testing

![Json Highlighting](https://github.com/tyrolite-studios/apixt/assets/173810867/0d5909a4-bbe1-4418-b448-3a92d546f5a3)

**Comment by mstein77** [comment]
Ja, das hatte ich vergessen zu erwähnen, du kannst git flow init mit den default-einstellungen initialisieren und dann darüber dann feature starten
